### ISSUE TITLE
Add new description for serverless function create webview

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3036]
Description:

The OpenShift Serverless Functions support enables developers to create, build, run, invoke and deploy serverless functions on OpenShift, providing a seamless development experience with the latest kn and func CLI tool integrated.

Heading:

OpenShift Serveless Functions

**Comment by mohitsuman** [comment]
Relates to #2993

**Comment by msivasubramaniaan** [comment]
Done with https://github.com/redhat-developer/vscode-openshift-tools/pull/3003

**Comment by mohitsuman** [comment]
@msivasubramaniaan I still see the wordings are old ones.

<img width="1508" alt="Screenshot 2023-07-25 at 2 55 17 AM" src="https://github.com/redhat-developer/vscode-openshift-tools/assets/3133356/5fbe2b49-23e7-41e0-ae0a-80e6d4e40c9c">

Can you please raise a new PR and update this.

**Comment by msivasubramaniaan** [comment]
> @msivasubramaniaan I still see the wordings are old ones.
> 
> <img alt="Screenshot 2023-07-25 at 2 55 17 AM" width="1508" src="https://user-images.githubusercontent.com/3133356/255724690-5fbe2b49-23e7-41e0-ae0a-80e6d4e40c9c.png">
> Can you please raise a new PR and update this.

@mohitsuman added description as per your commit suggestion https://github.com/redhat-developer/vscode-openshift-tools/pull/3003#discussion_r1271142666
